### ISSUE TITLE
State count renderer for all states in the model

### ISSUE THREAD

**Issue by giovannic** [mrc-ide/hypatia#10]
As mentioned in #2 

You can use the [individual prefab](https://mrc-ide.github.io/individual/reference/state_count_renderer_process.html) here

**Comment by giovannic** [comment]
@giovannic generalise this for the individual package

**Comment by giovannic** [comment]
document it

**Comment by giovannic** [comment]
consider generalising incidence too 🤔

**Comment by richfitz** [comment]
Being done in #37
