### ISSUE TITLE
Model transition probabilities from erlang distribution

### ISSUE THREAD

**Issue by giovannic** [mrc-ide/hypatia#28]
Stochastic scheduling based on the erlang distribution.

Note: make sure schedules are cleared when individuals die

You can look at malaria model for reference

**Comment by giovannic** [comment]
OJ does this in his branch [here](https://github.com/mrc-ide/hypatia/blob/dev/oj_refactor/R/processes.R#L46-L283)

It also requires create_events, create_infection_update_listener and parameters from #4.

We want to test that:

 * create_event_based_processes configures create_infection_update_listener correctly
 * create_infection_update_listener updates the population correctly
 * can an individual be scheduled twice in the same timestep?

**Comment by ceeb950** [comment]
close  #28
