### ISSUE TITLE
Vignette to compare hypatia and squire outputs

### ISSUE THREAD

**Issue by giovannic** [mrc-ide/hypatia#3]
We need an easy way to validate the implementation of hypatia.

We can create a vignette which plots both prevalence curves for 2 years in the conditions from #2 

>     Epidemics to be simulated for 1 fixed value of R0 over time
>     Epidemics to be simulated for any countries contained in squire::population
>     Epidemics assumed to have infinite healthcare capacity

We can compare for R0 = c(2, 3, 4) and countries = c('India', 'Nigeria', 'Panama')

**Comment by giovannic** [comment]
Work off the vignette in dev/oj_refactor

**Comment by giovannic** [comment]
Do multiple simulations

**Comment by ceeb950** [comment]
close  #3
