### ISSUE TITLE
Parameterise the model with squire parameters

### ISSUE THREAD

**Issue by giovannic** [mrc-ide/hypatia#4]
As mentioned in #2 

> Use the country name (e.g. "Iran") to create our parameter set, psq, using psq <- hypatia::parameters_explicit_SEIR(country = "Iran")

We need to create and test a function to take paramters from squire and pass them into individual.

NOTE: individual can only take numeric scalars and vectors as parameters, so we will have to encode any strings.

**Comment by OJWatson** [comment]
Should be fine as the country string names are just used to be passed to `squire` functions that fetch numeric scalars and vectors for the parameters.
